/*
 * Unit tests for webview/node-text-fallback/svg-postprocess.ts.
 * The fixture mirrors real dvisvgm 3.x output (single quotes, defs ids,
 * xlink:href references). No TeX toolchain required.
 *
 * Run with:  npm test   (in vscode-extension/)
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { toSnippetRenderPayload } from "../webview/node-text-fallback/svg-postprocess";

const DVISVGM_FIXTURE = [
  "<?xml version='1.0' encoding='UTF-8'?>",
  "<!-- This file was generated by dvisvgm 3.2.1 -->",
  "<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='25.653pt' height='8.539pt' viewBox='0 0 25.653 8.539'>",
  "<defs>",
  "<path id='g0-172' d='M4.9-.09H4.15Z'/>",
  "<path id='g1-68' d='M1.75-4.25Z'/>",
  "</defs>",
  "<g id='page1'>",
  "<use x='0' y='-.712' xlink:href='#g0-172'/>",
  "<use x='8.53' y='-.711' xlink:href='#g1-68'/>",
  "</g>",
  "</svg>",
].join("\n");

test("viewBox と body が抽出される", () => {
  const payload = toSnippetRenderPayload("native:key1", DVISVGM_FIXTURE);
  assert.ok(payload);
  assert.deepEqual(payload.viewBox, { x: 0, y: 0, width: 25.653, height: 8.539 });
  assert.ok(payload.body.includes("<path"));
  assert.ok(payload.body.includes("<use"));
  assert.ok(!payload.body.includes("<?xml"));
  assert.ok(!payload.body.includes("<svg"));
  assert.ok(!payload.body.includes("</svg>"));
});

test("id と参照が cacheKey 固有のプレフィックスでリネームされる", () => {
  const payload = toSnippetRenderPayload("native:key1", DVISVGM_FIXTURE);
  assert.ok(payload);
  // 元の裸の id は残らない
  assert.ok(!/id='g0-172'/.test(payload.body));
  assert.ok(!/xlink:href='#g0-172'/.test(payload.body));
  // プレフィックス付きの id と参照が対応している
  const idMatch = payload.body.match(/id='(n[0-9a-f]{8}-)g0-172'/);
  assert.ok(idMatch, "prefixed id should exist");
  assert.ok(payload.body.includes(`xlink:href='#${idMatch[1]}g0-172'`));
});

test("異なる cacheKey は異なる id プレフィックスになる（断片間衝突の回避）", () => {
  const a = toSnippetRenderPayload("native:key1", DVISVGM_FIXTURE);
  const b = toSnippetRenderPayload("native:key2", DVISVGM_FIXTURE);
  assert.ok(a && b);
  const prefixA = a.body.match(/id='(n[0-9a-f]{8}-)/)?.[1];
  const prefixB = b.body.match(/id='(n[0-9a-f]{8}-)/)?.[1];
  assert.ok(prefixA && prefixB);
  assert.notEqual(prefixA, prefixB);
});

test("currentColor 継承: 全体が fill=currentColor の <g> に包まれ、明示黒も置換される", () => {
  const withBlack = DVISVGM_FIXTURE.replace(
    "<use x='0' y='-.712' xlink:href='#g0-172'/>",
    "<use x='0' y='-.712' fill='#000' xlink:href='#g0-172'/><rect fill='red' stroke='black' width='1' height='1'/>"
  );
  const payload = toSnippetRenderPayload("native:key1", withBlack);
  assert.ok(payload);
  assert.ok(payload.body.startsWith('<g fill="currentColor"'));
  assert.ok(payload.body.endsWith("</g>"));
  assert.ok(payload.body.includes("fill='currentColor'"));
  assert.ok(payload.body.includes("stroke='currentColor'"));
  // 黒以外の明示色は温存
  assert.ok(payload.body.includes("fill='red'"));
});

test("url(#...) 参照もリネームされる", () => {
  const withUrl = DVISVGM_FIXTURE.replace(
    "<g id='page1'>",
    "<clipPath id='clip1'><rect width='1' height='1'/></clipPath><g id='page1' clip-path='url(#clip1)'>"
  );
  const payload = toSnippetRenderPayload("native:key1", withUrl);
  assert.ok(payload);
  assert.ok(!/url\(#clip1\)/.test(payload.body));
  assert.ok(/url\(#n[0-9a-f]{8}-clip1\)/.test(payload.body));
});

test("viewBox の無い / 壊れた SVG には null を返す", () => {
  assert.equal(toSnippetRenderPayload("k", "<svg width='1'></svg>"), null);
  assert.equal(toSnippetRenderPayload("k", "not svg at all"), null);
  assert.equal(toSnippetRenderPayload("k", "<svg viewBox='0 0 0 0'></svg>"), null);
});
